### ISSUE TITLE
Mention rsync for file transfer

### ISSUE THREAD

**Issue by drkrynstrng** [hpc-carpentry/hpc-intro#100]
I think it is worth mentioning `rsync` as an alternative to `scp` and to include some basic information about it on an Extras page (see also #27). It is arguably too advanced for an intro course, given its many options, but as new users become more experienced with HPC they will likely find `rsync` to be a better tool for transferring files. The basic syntax is similar to `scp`, but It is typically faster and easier to use when transferring large and/or many files and creating backups.

**Comment by psteinb** [comment]
Great idea. This could go into a callout box. Feel free to submit a PR. Thanks!

**Comment by psteinb** [comment]
Closing in favor of #106. Please reopen if needed.
