### ISSUE TITLE
Diagram to show the path from laptop to cluster

### ISSUE THREAD

**Issue by Sabryr** [hpc-carpentry/hpc-intro#105]
For a group of first time users a diagram that showed that they need to connect to a computer on the other side of the internet and that is what ssh doing, made the start of the conversation more friendlier. If you think this is something useful I can send a PR. This also provided me a way to use the same diagram later on when showing the difference between login node and compute node 

The diagram in question is  depicted here :https://sabryr.github.io/hpc-intro/12-cluster/index.html

**Comment by psteinb** [comment]
I typically do this on the whiteboard. I think this is a good idea and it would be a good placeholder for people with artistic affections to help in the future. I'd encourage you to send a PR, but please base your submission on the [lesson outline](https://github.com/hpc-carpentry/hpc-intro/blob/gh-pages/lesson-outline.md).

**Comment by Sabryr** [comment]
OK. I will send this as soon as the blocking PR are resolved

**Comment by tkphd** [comment]
Since whiteboards are a thing of the past, let's move forward with this.

**Comment by Sabryr** [comment]
Lot of activity here and very encouraging, sorry that I could not be more proactive due to holidays.

**Comment by tkphd** [comment]
Thanks, and no pressure! Whenever you have time & energy to commit, it'll be nice to see.

**Comment by psteinb** [comment]
I second what @tkphd mentioned.
