### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by Sabryr** [hpc-carpentry/hpc-intro#107]
https://hpc-carpentry.github.io/hpc-intro/12-cluster/index.html 

", Lola is asked to use a file of her liking and transfer" URL is  https://hpc-carpentry.github.io/hpc-intro/filesystem/home/admin/this_weeks_canteen_menus/todays_canteen_menu.pdf  Which is missing. 

(Too bad I can not get the code link for md files)

**Comment by Sabryr** [comment]
May be create a simple file with echo here (instead of downloading one)
 echo "Test transfer from Laptop " >  from_laptop.txt
or
 echo "Test transfer from $HOSTNAME on " $(date) >  from_laptop.txt

Then transfer from_laptop.txt to the cluster

**Comment by Sabryr** [comment]
With the PDF, it is not possible to view on cluster either  (at this stage of the lessons)

**Comment by psteinb** [comment]
This is mostly a placeholder. We can change this at any time. But I am afraid that #101 will remove all of Lola. Not sure if
this piece will be left on the table.

**Comment by Sabryr** [comment]
Yes #101 is show stopper at the moment. Our lessons have migrated much away from the central one. It will be very helpful if #101 is finalized.  IMO I am still thinking a pdf is not a good choice, simple text would be better

**Comment by psteinb** [comment]
I agree.

**Comment by aturner-epcc** [comment]
I think this issue is not relevant to the material at the moment. If this example comes back in then quality control should pick up if the link works or not.

Suggest we close this for now.

**Comment by Sabryr** [comment]
I agree
