### ISSUE TITLE
tar is introduced twice

### ISSUE THREAD

**Issue by aturner-epcc** [hpc-carpentry/hpc-intro#108]
`tar` is introduced in both `15-transferring-files` and `17-responsibility` with no reference between them.

**Comment by aturner-epcc** [comment]
Potentially, the solution is to mention in 15 that this will be discussed in more detail in 17...

**Comment by psteinb** [comment]
Good idea. I would add a callout in 15 with 3-4 lines about tar and potentially some short examples.

**Comment by psteinb** [comment]
closing this in favor of #111
