### ISSUE TITLE
Make lessons less system-specific

### ISSUE THREAD

**Issue by jstaf** [hpc-carpentry/hpc-intro#12]
With the goal of these materials being more widely applicable, we should remove system-specific details and replace them with more general explanations.

**Comment by pdoehle** [comment]
Is there a way for instructors to clone materials and use Jekyll to drop their own system information into the lesson material?

**Comment by ChristinaLK** [comment]
Yes! @psteinb did this for hpc-in-a-day and I think this should be a development priority if possible.  You can do it either by variables in the `_config.yml` file or by having snippets in the ` _includes/` folder (or both).

**Comment by ChristinaLK** [comment]
Also, based on conversations at PEARC, this is definitely something we should work through, as it's going to be key in making these materials useful to a large number of people.

**Comment by tkphd** [comment]
I believe that these issues are addressed by the recent efforts to (1) template lessons and (2) build a library of site-specific output snippets. @jstaf, are these efforts satisfactory?
