### ISSUE TITLE
Setup suggestion - Usage of Powershell as an alternative option for Windows

### ISSUE THREAD

**Issue by tarunbonu** [hpc-carpentry/hpc-intro#122]
Hi there!

Powershell is available on Windows which can be used to execute the ssh command. This can be provided as an alternative option for the installation of Xterm. This might make it a lot easier for Windows users to access the HPC cluster.

**Comment by psteinb** [comment]
Thanks for the contribution. Most of us are non-Windows users and rely on these kind of feedback. Feel free to open a PR, please.

**Comment by tkphd** [comment]
Addressed in f4548ae.
