### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#131]
`_extras/18-nextsteps` suggests downloading "ion-channel.tpr" from `/files/`, but that file does not exist in `_includes`. If anyone has a copy, please check it in under `_includes/ion-channel.tpr`. If not, we'll have to remove that segment.

**Comment by psteinb** [comment]
@aturner-epcc can you please have a look?

**Comment by aturner-epcc** [comment]
@tkphd @psteinb I have a copy. Sorry this did not make it back into the main repo with the other material. One quick question: as the episode mentions it in `files/`, should I not put it in this directory rather than `_includes/`?

**Comment by tkphd** [comment]
That's great @aturner-epcc, thanks!
When Jekyll builds the site, it copies everything from `_includes` into `_site/files`, and serves them from there. So, please restore `ion-channel.tpr` (and `parallel_example.tar.gz` if you have a copy) to `_includes`.
