### ISSUE TITLE
queues and default partition error

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#150]
In order to "be kind to the scheduler," it's good practice to specify, at absolute minimum, which partition a job will run on, and the upper bound on how much time it should take. Indeed, on clusters without a default queue configured, our first job will fail!

- [x] Introduce `sched.queue.batch` and `sched.queue.interactive` in `_config.yml`, replacing `workshop_interactive_queues` which nobody has used.
- [x] Introduce error thrown when a partition is not specified, and no default has been set.
- ~Add partition and time limit flags to the "example job", and propagate throughout.~

**Comment by psteinb** [comment]
I like the motivation behind this issue. The current content in [the scheduler lesson](https://hpc-carpentry.github.io/hpc-intro/13-scheduler/index.html) does comment on the availability of flags, but doesn't make use of them. Which I believe is a didactically fragile approach. I hence would split this issue. Keep the first 2 tasks in this one and open a separate issue for the last item revolving around adding to the flow of the lesson. Would that be ok, @tkphd ?

**Comment by tkphd** [comment]
In the interests of keeping the first job as simple as possible, sure -- so long as we're clear that's the intention.
This is introducing less-than-best-practice off the bat, which is unfortunate, but from a pedagogical perspective it's better to not overwhelm the learners with a bunch of rules up front.
