### ISSUE TITLE
snippet names are confusing

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#151]
It's very difficult to track down which snippet one must edit to port or correct the output. Partially, this stems from reuse of "example_job.sh", requiring the lesson to use the contents of that file as it changes to specify snippets.

A better approach would be to write one shell script per job, copying old ones where appropriate, and using the script name to inform the snippet name. If we're very clever, the naming could escalate alphabetically...

**Comment by psteinb** [comment]
:+1: We should do this!

**Comment by tkphd** [comment]
OK -- after #148 and #149 are dealt with (merged or rejected), to minimize merge conflicts.

**Comment by tkphd** [comment]
To make this repeatable on derivative works, I'm writing a shell script to do the renaming. This script will be checked in to the snippets library; at some point in the future, it should be deprecated & removed.
