### ISSUE TITLE
Propose to jump version from Alpha to Beta  

### ISSUE THREAD

**Issue by Sabryr** [hpc-carpentry/hpc-intro#174]
Materiel are good to be taught now and deserves more than alpha

**Comment by tkphd** [comment]
Let's plan to vote on this at the first Task Force meeting in September.

**Comment by tkphd** [comment]
Created and added an agenda item on the [hpc-intro wiki](https://github.com/hpc-carpentry/hpc-intro/wiki)

**Comment by psteinb** [comment]
I agree with @tkphd as much as I enjoy your comment @Sabryr. I would keep it in Alpha for now and see what the task force thinks. I suggest to close this issue.
