### ISSUE TITLE
Do we need a Bash/Zsh distinction in Setup?

### ISSUE THREAD

**Issue by mikerenfro** [hpc-carpentry/hpc-intro#192]
Related to shell-novice [#978](https://github.com/swcarpentry/shell-novice/issues/978) and [#1033](https://github.com/swcarpentry/shell-novice/issues/1033), are we doing anything on the local system that is Bash-specific? A quick skim looks like we're doing nothing but running ssh, scp, rsync, and other executables to interact with the HPC, and nothing in terms of scripting.

**Comment by psteinb** [comment]
to the best of my knowledge, no. We stay rather general in using the shell AFAIK.

**Comment by tkphd** [comment]
Indeed, the specific shell does not matter for this lesson. The discussion of bash vs zsh in the lesson setup is purely carried over from shell-novice; we can simplify that macOS section to just the bit about opening the Terminal app.
