### ISSUE TITLE
SITE_CONFIG is a vague env var name

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#195]
A more specific name would be preferable, when telling Make which site to build.

**Comment by tkphd** [comment]
Some ideas:

- `SWC_HPC_SITE_CONFIG`
- `HPC_CONFIG_YML`
- `HPC_SITE_CONFIG`

**Comment by reid-a** [comment]
I vote for `HPC_JEKYLL_CONFIG`, fwiw.

**Comment by tkphd** [comment]
I like it.
