### ISSUE TITLE
yourUsername variable

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#200]
At the moment, `yourUsername` is hard-coded in many episodes. This should be replaced by the template variable.

The template variable for the username is under the scheduler section. This is improperly scoped: the username is integral to the *remote*, not the *scheduler*.

This will be fixed (live!) during this evening's Task Force & Maintainers Tour.

**Comment by Sabryr** [comment]
I use $USER when on the cluster

**Comment by tkphd** [comment]
Cool! Set that (instead of "yourUsername") in your `_config_options.yml`, and it will render as you wish.
