### ISSUE TITLE
make lesson-check in testing

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#204]
`make lesson-check` does not run on the CI check. This step is helpful for catching, e.g., missing blockquote types. This is a small but significant oversight.

**Comment by ocaisa** [comment]
It does run I think, see https://github.com/hpc-carpentry/hpc-intro/blob/gh-pages/.github/workflows/test_and_build.yml#L41 though I'm not sure if that is exactly the same.

**Comment by ocaisa** [comment]
Could be pulled into a separate step though

**Comment by tkphd** [comment]
Well, isn't that interesting. `make lesson-check-all`, which we run, *does not* throw an error when it catches things. `make lesson-check`, on the other hand, *does*.

```bash
$ make lesson-check-all
./README.md: Line(s) end with whitespace: 22, 32, 35
./index.md: Line(s) too long: 13
./index.md:18: Unknown or missing blockquote type None
./index.md:29: Unknown or missing blockquote type None
./index.md:31: Unknown or missing blockquote type None
./index.md:34: Unknown or missing blockquote type None
./setup.md: Line(s) too long: 114

$ make lesson-check
./index.md:18: Unknown or missing blockquote type None
./index.md:29: Unknown or missing blockquote type None
./index.md:31: Unknown or missing blockquote type None
./index.md:34: Unknown or missing blockquote type None
make: *** [Makefile:134: lesson-check] Error 1
```

**Comment by ocaisa** [comment]
Yeah, I just checked up on it, there's a `--permissive` flag when you use `lesson-check-all` which means it doesn't return an error code, so I guess we want both? Check all includes checking line length and trailing whitespace, not much else extra

**Comment by ocaisa** [comment]
Other option is to remove the permissive flag in the Makefile for `make lesson-check-all`.

**Comment by tkphd** [comment]
Since we inherit `Makefile` from the upstream [styles](https://github.com/carpentries/styles/) repo, minimizing changes is preferable. I suggest running both `make lesson-check` and `make lesson-check-all`.
