### ISSUE TITLE
Parallel example to run?

### ISSUE THREAD

**Issue by reid-a** [hpc-carpentry/hpc-intro#214]
The death of seqtk reminds me that there's really nowhere in the lesson where a parallel task is executed by the learners.

I'm sympathetic to the argument (which I think I myself have made in the past) that this is impractical because MPI codes in general are not portable, so to have an example you can run you'd have to build it, and introducing building things is a large can of worms, and varies widely across systems.

Maybe somebody else has an idea of something learners could run that would demonstrate parallel processing?

For testing on my own clusters, I often use a simple "cpi.c" series expansion code that computes pi by a distributed series summation, borrowed from "examples" directory of the OpenMPI Debian package.

Feedback on whether this is too confusing or tangential would be welcome.

I was going to attach the file, but the issue template doesn't recognize the `.c` file type, so it'll be in-line in the first comment.

**Comment by reid-a** [comment]
Cpi.c file:

```
#include <mpi/mpi.h>
#include <stdio.h>
#include <math.h>
#include <time.h>

double f( double );

double f( double a)
{
    return (4.0 / (1.0 + a*a));
}

int main( int argc, char *argv[] )
{
    int done = 0, n, myid, numprocs, i;
    double PI25DT = 3.141592653589793238462643;
    double mypi, pi, h, sum, x;
    double startwtime=0.0, endwtime;
    int  namelen;
    char processor_name[MPI_MAX_PROCESSOR_NAME];

    MPI_Init(&argc,&argv);
    MPI_Comm_size(MPI_COMM_WORLD,&numprocs);
    MPI_Comm_rank(MPI_COMM_WORLD,&myid);
    MPI_Get_processor_name(processor_name,&namelen);

    fprintf(stderr,"Process %d on %s\n",
	    myid, processor_name);

    n = 0;
    while (!done)
    {
        if (myid == 0)
        {
/*
            printf("Enter the number of intervals: (0 quits) ");
            scanf("%d",&n);
*/
	    if (n==0) n=10000000; else n=0;

	    startwtime = MPI_Wtime();
        }
        MPI_Bcast(&n, 1, MPI_INT, 0, MPI_COMM_WORLD);
        if (n == 0)
            done = 1;
        else
        {
            h   = 1.0 / (double) n;
            sum = 0.0;
            for (i = myid + 1; i <= n; i += numprocs)
            {
                x = h * ((double)i - 0.5);
                sum += f(x);
            }
            mypi = h * sum;

            MPI_Reduce(&mypi, &pi, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);

            if (myid == 0)
	    {
                printf("pi is approximately %.16f, Error is %.16f\n",
                       pi, fabs(pi - PI25DT));
		endwtime = MPI_Wtime();
		printf("wall clock time = %f\n",
		       endwtime-startwtime);	       
	    }
        }
    }
    MPI_Finalize();
    return 0;
}
```

**Comment by mikerenfro** [comment]
I'm reluctant to throw C code at what my typical Carpentries audience would be, but below is a more annotated and compact version (assuming we're good to set n to a constant and use as many cores and nodes as make sense). Assumes the audience remembers numerical integration from calculus, and tries to de-jargon some of the variable names, since I don't think we're going deep into MPI at all:

```c
#include <mpi.h>
#include <stdio.h>
#include <math.h>
#include <time.h>

double f( double a)
{
  return (4.0 / (1.0 + a*a));
}

int main( int argc, char *argv[] )
{
  /* counter, total number of rectangles for estimate */
  int i, n = 10000000;
  /* for summing up all the rectangle areas, and target value for comparison */
  double subtotal, pi, h, heights = 0.0, x;
  double PI25DT = 3.141592653589793238462643;
  /* for timekeeping */
  double startwtime, endwtime;
  /* for worker group organization */
  int  namelen, myid, num_workers;
  char host_name[MPI_MAX_PROCESSOR_NAME];

  MPI_Init(&argc, &argv); /* Set up the group of workers */
  MPI_Comm_rank(MPI_COMM_WORLD, &myid); /* Which worker am I? */

  if (myid == 0)
  {
    startwtime = MPI_Wtime(); /* Worker 0 keeps track of time */
  }

  /* All workers report their ID and host they're running on */
  MPI_Get_processor_name(host_name, &namelen); /* What's my host's name? */
  printf("Worker %d on host %s starting.\n", myid, host_name);

  /* All workers use this method to sum up areas of rectangles */
  MPI_Comm_size(MPI_COMM_WORLD, &num_workers); /* How many workers exist? */
  h = 1.0 / (double) n; /* define the width of the rectangle */
  /* Each worker calculates the area of its rectangle, then skips past
     other workers' rectangles to its next one */
  for (i = myid + 1; i <= n; i += num_workers)
  {
    x = h * ((double)i - 0.5); /* Calculate the centerpoint of the rectangle */
    heights += f(x); /* Calculate the height of the rectangle, add to the total */
  }
  subtotal = h * heights; /* rectangular area subtotal for this worker */

  /* Sum up all the rectangular area subtotals */
  MPI_Reduce(&subtotal, &pi, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);

  if (myid == 0)
  {
    /* Worker 0 records time and prints all results to the screen */
    endwtime = MPI_Wtime();
    printf("pi is approximately %.16f, Error is %.16f\n", pi, fabs(pi - PI25DT));
    printf("wall clock time = %f\n", endwtime-startwtime);
  }
  MPI_Finalize(); /* Tear down the group of workers */
  return 0;
}
```

Tested on 2 nodes with 6 or 12 tasks each:

```
Worker 0 on host gpunode002 starting.
Worker 1 on host gpunode002 starting.
Worker 2 on host gpunode002 starting.
Worker 3 on host gpunode002 starting.
Worker 4 on host gpunode002 starting.
Worker 5 on host gpunode002 starting.
Worker 6 on host gpunode003 starting.
Worker 7 on host gpunode003 starting.
Worker 8 on host gpunode003 starting.
Worker 10 on host gpunode003 starting.
Worker 11 on host gpunode003 starting.
Worker 9 on host gpunode003 starting.
pi is approximately 3.1415926535897674, Error is 0.0000000000000258
wall clock time = 0.052589
```

```
Worker 3 on host gpunode002 starting.
Worker 4 on host gpunode002 starting.
Worker 7 on host gpunode002 starting.
Worker 1 on host gpunode002 starting.
Worker 2 on host gpunode002 starting.
Worker 5 on host gpunode002 starting.
Worker 8 on host gpunode002 starting.
Worker 9 on host gpunode002 starting.
Worker 10 on host gpunode002 starting.
Worker 0 on host gpunode002 starting.
Worker 11 on host gpunode002 starting.
Worker 6 on host gpunode002 starting.
Worker 12 on host gpunode003 starting.
Worker 15 on host gpunode003 starting.
Worker 16 on host gpunode003 starting.
Worker 17 on host gpunode003 starting.
Worker 18 on host gpunode003 starting.
Worker 20 on host gpunode003 starting.
Worker 22 on host gpunode003 starting.
Worker 13 on host gpunode003 starting.
Worker 14 on host gpunode003 starting.
Worker 19 on host gpunode003 starting.
Worker 21 on host gpunode003 starting.
Worker 23 on host gpunode003 starting.
pi is approximately 3.1415926535897913, Error is 0.0000000000000018
wall clock time = 0.034243
```

**Comment by colinsauze** [comment]
Why not use a Python based example to make it more accessible to the learners? Here's one I use, its not the same algorithm as above but also calculates Pi. Its too late on a Friday evening for me to convert C to Python, but I see no reason why the above code wouldn't convert easily.

`
#!/usr/bin/env python3
import sys
from mpi4py import MPI
import numpy as np

np.random.seed(2017)

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()


def inside_circle(total_count):

    hname = MPI.Get_processor_name()

    x = np.float32(np.random.uniform(size=total_count))
    y = np.float32(np.random.uniform(size=total_count))

    radii = np.sqrt(x*x + y*y)

    count = len(radii[np.where(radii<=1.0)])

    return count

def estimate_pi(n_samples):

    counts = inside_circle(n_samples)
    return (4.0 * sum(counts) / total_count)

if __name__=='__main__':

    n_samples = 10000
    if len(sys.argv) > 1:
        n_samples = int(sys.argv[1])

    if rank == 0:
        partitions = [ int(n_samples/size) for item in range(size)]
        counts = [ int(0) ] *size
    else:
        partitions = None
        counts = None

    partition_item = comm.scatter(partitions, root=0)
    count_item = comm.scatter(counts, root=0)

    count_item = inside_circle(partition_item)

    counts = comm.gather(count_item, root=0)
    if rank == 0:
        my_pi = 4.0 * sum(counts) / n_samples
        sizeof = np.dtype(np.float32).itemsize
        print("[     mpi version] required memory %.3f MB" % (n_samples*sizeof*3/(1024*1024)))
        print("[using %3i cores ] pi is %f from %i samples" % (size,my_pi,n_samples))
`

**Comment by reid-a** [comment]
These are both improvements IMO.

Annotating the Python version is probably a good answer. Learners probably don't need to know in detail how the code works, but should have a "block-diagram level" understanding of the parallel structure, so they can understand how they're exercising the cluster.

**Comment by mikerenfro** [comment]
Working on a Python translation of the numerical integration version in between other items today.

**Comment by ocaisa** [comment]
@psteinb has a mpi4py estimation of pi in his HPC novice lesson (some of that lesson has already been merged here in other parts): https://psteinb.github.io/hpc-in-a-day/bo-01-bonus-mpi-for-pi/

**Comment by reid-a** [comment]
@ocaisa That's encouraging, it eases my concern that introducing code at this level is a distraction.

I had no difficulty running the Python "darts in a circle" example on my laptop, so it passes the "acetic acid test". Looking forward to what @mikerenfo comes up with, also, but I'm thinking the circle example is almost trivial to explain, so it might be a good choice.

**Comment by mikerenfro** [comment]
Don't hold up any useful work on my account, so feel free to integrate the dots in a circle version as soon as you're happy with the code. I'd probably suggest reviewing whatever code is in that to make sure it doesn't use anything too far beyond what's in the normal SWC Python lessons.

I realize SWC won't talk about MPI, but I'd verify if list comprehensions, formatted prints, that sort of thing are covered. If not, converting them to a more novice-level equivalent would cut the new material down to just the MPI parts.

**Comment by reid-a** [comment]
I have done a bit more work on the candidate Python code, and I'm reasonably happy with the annotation, but I ran into a couple of issues, and I'd appreciate feedback.

- Clusters will vary in their version of Python. This bit me because I put in some `print(f"Message {data}")` items, but this formatted output is a post-Python 3.5 idiom, and generates a syntax error for the default `/usr/bin/python3` on a Debian 9 system, which as Python 3.5.
- The reason I was running the defaults was that my cluster does not have a system-wide Conda environment. Setting up Conda is definitely out of scope for this lesson, so system defaults are what we have to work with.

My concern is that by going with a Python example, we've opened a can of worms related to versioning. It's still possible to proceed, with e.g. conservative choices for the `print` statements, but I'm wondering if others are troubled by this.

My own instincts are that the C version, being closer to the metal, is more robust, but the flip side of that is that these are the instincts of an experienced dev-ops person with lots of C experience, and not those of our typical learners.

Comments?

**Comment by tkphd** [comment]
Consider using `from __future__ import print_function` to solve this particular snag. It should fix it for Python species below v3.5; above, it's a no-op.

I would rather stick to Python, since it's high-level.

**Comment by reid-a** [comment]
The print issue is not critical in itself, unless it's a warning sign about a morass of distracting dependency issues that takes away from the value of using a high-level language.

For what it's worth, the `__future__` trick does not appear to work in the obvious way for what I want, which is to have the Python 3.6+ formatting idiom available in Python 3.5. Docs I can find on-line suggest it's better suited to making the Python 3 style print function available to Python 2 codes, and in my simple testing, that *does* work in the obvious way.

I will take the foregoing comment primarily as a vote for sticking with Python, though, which is helpful feedback.

**Comment by mikerenfro** [comment]
(My apologies for my absence, work got busy lately. Replying over email, hopefully this goes through.)

Thought I’d mentioned this earlier, but I couldn’t find it. I’d suggest erring on the side of simple, and only using concepts that are Introduced in the basic SWC Python lessons. So even though we don't cover MPI there, import statements are used, and are fine.

So IIRC, that would mean avoiding formatted prints in favor of print(“a =“, a), no list comprehensions, etc.

That way, we keep the cognitive load down to the algorithm and the MPI calls.

**Comment by reid-a** [comment]
@mikerenfro No worries, things are not moving super-fast here.

I concur with your idea of erring on the side of simplicity. This creates a bit of work, the example code I am working with uses Numpy arrays, which I'm confident are not covered in basic SWC Python, but I think I can probably get something reasonably comprehensible and functional fairly soon.

**Comment by mikerenfro** [comment]
Numpy shows up pretty early, actually, so no problem in using it instead of a list: https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html
