### ISSUE TITLE
Rename snippet library sub-directories

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#226]
At present, each of the sub-directories of each site's snippet catalog (to extend the library metaphor) is named with the numerical value of the lesson it goes with. However, as we see in #225, when new material is inserted, these numbers go out of sync. This is nightmarish to maintain, especially given the number of forks and pull requests that would need updating any time the lesson order changed.

Recommend finding a content-based naming scheme, with some verbosity, to improve maintainability & legibility. Related to #9.

## Current

| File Name                | Title                              | Snippet Folder Name |
| ---                      | ---                                | ---                 |
| 11-hpc-intro.md          | Why use a Cluster?                 | 11                  |
| 12-cluster.md            | Working on a remote HPC system     | 12                  |
| 13-scheduler.md          | Scheduling jobs                    | 13                  |
| 14-modules.md            | Accessing software                 | 14                  |
| 15-transferring-files.md | Transferring files                 | 15                  |
| 16-resources.md          | Using resources effectively        | 16                  |
| 17-responsiblity.md      | Using shared resources responsibly | 17                  |

## PR #225

| File Name                | Title                              | Snippet Folder Name |
| ---                      | ---                                | ---                 |
| 11-hpc-intro.md          | Why use a Cluster?                 | 11                  |
| 12-cluster.md            | Working on a remote HPC system     | 12                  |
| 13-scheduler.md          | Scheduling jobs                    | 13                  |
| 14-modules.md            | Accessing software                 | 14                  |
| 15-transferring-files.md | Transferring files                 | 15                  |
| 16-parallel.md           | Running a parallel job             | pll                 |
| 17-resources.md          | Using resources effectively        | 16                  |
| 18-responsiblity.md      | Using shared resources responsibly | 17                  |

## Proposed

| File Name                | Title                              | Snippet Folder Name |
| ---                      | ---                                | ---                 |
| 10-hpc-intro.md          | Why use a Cluster?                 | intro               |
| 15-cluster.md            | Working on a remote HPC system     | cluster             |
| 20-scheduler.md          | Scheduling jobs                    | scheduler           |
| 25-modules.md            | Accessing software                 | modules             |
| 30-transfers.md          | Transferring files                 | transfers           |
| 35-parallel.md           | Running a parallel job             | parallel            |
| 40-resources.md          | Using resources effectively        | resources           |
| 45-responsiblity.md      | Using shared resources responsibly | responsibility      |

We would need to modify the lesson-check script to let increasing
numbering sequences to pass, otherwise tests will break.

**Comment by Sabryr** [comment]
It will be convenient if the snippet and lesson have the same name. For example:

10-hpc-intro.md | Why use a Cluster? | intro

I would say 
10-hpc-intro.md | Why use a Cluster? | 10-hpc-intro

**Comment by reid-a** [comment]
@Sabryr I'm afraid that including the number defeats part of the purpose of the change. I'm on-board with:

10-hpc-intro.md | Why use a Cluster? | hpc-intro

i.e. the snippet directory name could exactly match the text part of the base of the lesson file name.

@tkphd  What are the modifications required to the lesson-check script?

**Comment by tkphd** [comment]
Thanks for the feedback, @Sabryr and @reida. I tend to prefer @reida's suggestion for the first lesson, producing

| File Name                | Title                              | Snippet Folder Name |
| ---                      | ---                                | ---                 |
| 10-hpc-intro.md | Why use a Cluster? |	hpc-intro |
| 15-cluster.md            | Working on a remote HPC system     | cluster             |
| 20-scheduler.md          | Scheduling jobs                    | scheduler           |
| 25-modules.md            | Accessing software                 | modules             |
| 30-transfers.md          | Transferring files                 | transfers           |
| 35-parallel.md           | Running a parallel job             | parallel            |
| 40-resources.md          | Using resources effectively        | resources           |
| 45-responsiblity.md      | Using shared resources responsibly | responsibility      |

I think the easiest "fix" for lesson-check is to drop [lines 299 to 307](https://github.com/hpc-carpentry/hpc-intro/blob/aeb857f5ff2366156e94a6ab5912c55a750857de/bin/lesson_check.py#L299).

**Comment by tkphd** [comment]
Issue opened [upstream](https://github.com/carpentries/styles/issues/502).

**Comment by jevbelikov** [comment]
+1 for content-based naming; perhaps we could drop the number from file names too? this would also make reordering easier.

**Comment by tkphd** [comment]
Good prompt, @jevbelikov. If we want to, we can migrate to [manual episode order](https://github.com/carpentries/styles/blob/gh-pages/_includes/manual_episode_order.html), and name the Markdown files anything we like. This introduces a small maintenance & training overhead, since the existence and significance of the new `episode_order` array in `_config.yml` must be clearly explained. This would improve flexibility, though I'm sure there will be vigorous discussion of a new naming scheme were we to go this route.

**Comment by reid-a** [comment]
For what it's worth, notwithstanding the limited ambition of my PR, I am not opposed to nonsequential numbering, or to removing the numbers and doing manual sequencing. I left that out mostly based on uncertainty about how to coordinate with upstream on those issues.

**Comment by reid-a** [comment]
Closed in favor of #230
