### ISSUE TITLE
Accessibility issue with main web site

### ISSUE THREAD

**Issue by karres-illinois** [hpc-carpentry/hpc-intro#227]
Hello,

I know this is not specifically about this "repo" but I visited the main web site (https://hpc-carpentry.github.io/about) and It is extremely hard for me to read that site text.  I was unable to find contact email addresses for a site maintainer but it seemed to suggest raising issues here.

The specific problems are that the font used for paragraphs is perhaps grey(?).  It sinks into the white background of the page.  Adding to the issue is that the font choice is extremely thin and spidery.

Please use black text on white backgrounds (actually most light/translucent backgrounds) and "normal" font weights.

Cheers

**Comment by reid-a** [comment]
This is a good point, and mentioning it here is a good way to get it some attention.

The repo that generates that page is a peer of this one, it's [here](https://github.com/hpc-carpentry/hpc-carpentry.github.io). Would you be willing to also open an issue there?

**Comment by karres-illinois** [comment]
Happy to open the issue in the right place, thanks 😊


--
Dean Karres
Sr Research Programmer, Beckman Institute
Illinois XSEDE Campus Champion
https://campuschampions.web.illinois.edu/

**Comment by psteinb** [comment]
Closing this in favor of 
https://github.com/hpc-carpentry/hpc-carpentry.github.io/issues/22
Please reopen at will.
