### ISSUE TITLE
line length and episode numbering

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-intro#35]
`make lesson-check-full` flags the following issues, after updating the backend (#34):

- [x] `Missing or non-consecutive episode numbers [0, 11, 12, 13, 14, 15, 16] `
  - related to #9
- [x] `./CODE_OF_CONDUCT.md: Internally-defined links may be missing definitions: "Carpentry Code of Conduct"=>"coc", "reporting guidelines"=>"coc-reporting"`
- [x] `./CONTRIBUTING.md: Line(s) are too long: 114, 126`
- [x] `./README.md: Line(s) are too long: 41, 42, 43, 46, 47, 53, 61, 69, 77`
- [x] `./_episodes/00-hpc-intro.md: Line(s) are too long: 124, 127`
- [x] `./_episodes/11-cluster.md: Line(s) are too long: 71, 87, 89, 90, 91, 99`
- [x] `./_episodes/12-scheduler.md: Line(s) are too long: 89, 91, 153, 154, 188, 190, 266, 267, 280, 302, 323, 348`
- [ ] `./_episodes/13-modules.md: Line(s) are too long: 91, 121, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 366`
- [x] `./_episodes/13-modules.md:434: Unknown or missing code block type None`
- [x] `./_episodes/14-transferring-files.md: Line(s) are too long: 47, 190, 195, 224`
- [x] `./_episodes/15-resources.md: Line(s) are too long: 89, 151, 153, 207`
- [x] `./_episodes/16-responsiblity.md: Line(s) are too long: 48`
- [x] `./index.md: Line(s) are too long: 7, 8, 12, 13`
- [x] `./index.md:18: Unknown or missing blockquote type None`
  - fixed by #33

**Comment by psteinb** [comment]
fine with me!
