### ISSUE TITLE
Worker node vs Compute node: regional dialect ?

### ISSUE THREAD

**Issue by baberlevi** [hpc-carpentry/hpc-intro#56]
12-cluster refers to 'worker (or execute)' nodes. We (and most other US institutions I've worked with) seem to refer to them as the 'compute' nodes. Minor difference that may be regional.

Do we need to think about regional dialect being swapped like cluster names & schedulers ? Or should we just keep adding terms (worker aka execute aka compute) ?

**Comment by ChristinaLK** [comment]
I think it would be good to use a consistent term, but describe alternatives when it's being introduced.

**Comment by tkphd** [comment]
This seems like a useful set of terms to define in the [glossary](https://github.com/hpc-carpentry/hpc-intro/blob/gh-pages/reference.md). Updated #37.
