### ISSUE TITLE
login node limits

### ISSUE THREAD

**Issue by baberlevi** [hpc-carpentry/hpc-intro#63]
17-responsibility says: 'A “quick test” is generally anything that uses less than 10GB of memory, 4 CPUs, and 15 minutes of time. Remember, the login node is to be shared with other users.'

This is going to vary widely by site. Many will have enforced ulimit or cgroup limits on the headnode that are significantly lower than this and may cause this type of 'quick test' to fail when it runs out of memory. 

How about just, don't run on the login node, and explain about looking for a debug or interactive queue ?

**Comment by psteinb** [comment]
Good idea, please submit a PR.
