### ISSUE TITLE
setup jekyll baseurl/relative_url

### ISSUE THREAD

**Issue by Carreau** [hpc-carpentry/hpc-intro#67]
most of the image are broken as they try to load from `/fig/` instead of `/hpc-intro/fig/...` this seem to be due to the missing `baseurl` config. 

It [seem like](https://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/#2-relative_url-and-absolute_url-filters) you can use filters to prepends only on github, and not when deploying/testing locally.

**Comment by Carreau** [comment]
> Checking other carpentries [sites](https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/03-create.md), I see that `[](../fig/motivatingexample.png)` is used.

I guess it might be possible, but wouldn't `../fig/motivatingexample.png`  break `jekyll serve` locally ?

**Comment by psteinb** [comment]
It doesn’t, but I believe that using liquid variables feels better.

**Comment by tkphd** [comment]
@psteinb, I believe `{{ site.url }}/fig/image.png` is preferred.

**Comment by psteinb** [comment]
The let's stick to `{{ site.url }}/fig/image.png`. We need to document this inside [lesson-outline.md] or somewhere similar.
