### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by Sabryr** [hpc-carpentry/hpc-intro#75]
https://github.com/hpc-carpentry/hpc-intro:

Under "Lesson structure"
 "full guide"  points to http://swcarpentry.github.io/lesson-example/04-formatting/  (404)

**Comment by Sabryr** [comment]
Thank you. Do you think some of the following should be fixed as well ?
git grep swcarpentry

CONTRIBUTING.md:1.  If you wish to change this lesson, please work in <https://github.com/swcarpentry/FIXME>, which
CONTRIBUTING.md:    can be viewed at <https://swcarpentry.github.io/FIXME>.
CONTRIBUTING.md:[swc-issues]: https://github.com/issues?q=user%3Aswcarpentry
README.md:[Software Carpentry example lesson](http://swcarpentry.github.io/lesson-example/).
README.md:([example](http://swcarpentry.github.io/r-novice-gapminder/)). We've got 4 major sections, each
README.md:formatting- see here for a [full guide](http://swcarpentry.github.io/lesson-example/04-formatting/).
README.md:[here](http://swcarpentry.github.io/lesson-example/setup/).
README.md:* [Example Bash lesson](https://github.com/swcarpentry/shell-novice)
README.md:* [Example Python lesson](https://github.com/swcarpentry/python-novice-inflammation)
README.md:* [Example R lesson](https://github.com/swcarpentry/r-novice-gapminder) (uses R markdown files
_config.yml:swc_github: "https://github.com/swcarpentry"
_config.yml:swc_pages: "https://swcarpentry.github.io"
_includes/links.md:[python-gapminder]: https://swcarpentry.github.io/python-novice-gapminder/
_includes/links.md:[swc-releases]: https://github.com/swcarpentry/swc-releases
index.md:> https://swcarpentry.github.io/shell-novice/ if new to the terminal.

**Comment by psteinb** [comment]
@Sabryr go for it! Any help is appreciated.
