### ISSUE TITLE
Resources - How Much to Request?

### ISSUE THREAD

**Issue by pereobo** [hpc-carpentry/hpc-intro#85]
Lesson: Using resources effectively
Section: Estimating required resources using the scheduler

I'd like to suggest a change and an expansion of the following.

"A good rule of thumb is to ask the scheduler for more time and memory than your job can use. This value is typically two to three times what you think your job will need."

I agree that the user should ask for more than they expect to need but I think two-to-three times is far too high.  When giving workshops to HPC novices I usually recommend no more than 20% (assuming the job's resource use is not unusually volatile) in order to ensure that a job does not get stuck in the queue waiting for the requested resources to become available.

How about something like this?  I think this is an important enough concept that it is worth spelling out the issues.

"A good rule of thumb is to ask the scheduler for more time and memory than you expect your job to need.  This ensures that minor fluctuations in run time or memory use will not result in your job being canceled by the scheduler.  Recommendations for how much extra to ask for vary but 10% is probably the minimum, with 20-30% being more typical.  Keep in mind that if you ask for too much, your job may not run even though enough resources are available, because the scheduler will be waiting to match what you asked for."

Could also add the following example to make the point even clearer.

"For example, suppose your job requires 20 GB of memory but you requested 60 GB just to be on the safe side.  While your job is waiting in the queue, a node with 40 GB becomes available but your job still doesn't start because the scheduler is looking for 60 GB to satisfy the requirements you specified.  In this case a smaller memory request would have resulted in your job starting sooner."

I think this point is worth emphasizing, especially as (in my experience, anyway) it isn't uncommon for novice users to end up with submit files containing resource requests that are far above what they actually need, which results in longer wait times as well as wasted resources, especially memory, when the jobs don't use what has been set aside for them.

Thoughts?

**Comment by ChristinaLK** [comment]
@pereobo sorry for the delay -- I guess most of us who typically watch this repository were busy last month!  

I agree with your suggested change. 2-3 times sounds way too high for me as well, and I think you've provided a clear alternative!

**Comment by aturner-epcc** [comment]
Addressed by #109 . Closing.
