### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Afrah-Khairallah** [hpc-carpentry/hpc-intro#89]
Introduction to High-Performance Computing                                          
Link : https://hpc-carpentry.github.io/hpc-intro/

Episode 1:  Why Use a Cluster?
Typos : line 54 (tell **the the** computer)
line 66: When the task to solve become **more heavy** on computations
Episode 2: Working on a cluster
line 179:  **Issueing** a `ssh` command always entails the same ....

Introduction to High-Performance Computing
Link : https://epcced.github.io/hpc-intro/

Episode: Why use High Performance Computing?
line 26 : Summarise your discussion in 2-3 **sentances**.
line 53:  They are often **interchangably** 
line 62: For example, varying an **imput** parameter (or input data) to a computation and running many copies simultaneously.
line 97:  Summarise your discussion in 2-3 **sentances**.

Episode: What is an HPC system?
line 43 : Each core contains a *floating point unit (FPU)* which is responsible for actually **performning** the computations 
line 51 : (also referred to as *RAM* or *DRAM*) in **addtion** to the processor memory 
line 79 : hey may need **differnt** options or settings
line 101 : performance and **workfows** are often categorised 
line 103 : his is typically seen when **peforming**

Episode: Connecting to the HPC system
line 9: "**Succesfully** connect to a remote HPC system."
line 90: Running PuTTY will not initially produce a terminal but **intsead** a window full of connection options.
line 175 :  then use the **follwing** command: `$ hostname`.

Episode: Transferring files
line 8: "Be able to **tranfer** files to and from a remote HPC system."
line 19: choose will be decided by what is most **covenient** for your workflow.
line 83: Or perhaps we're simply not sure which files we want to **tranfer** yet.
line 288: All file **tranfers** using the above methods use encrypted communication over

Episode: Scheduling jobs

line 248:  A key job **enviroment** variable in PBS is..
line 325: Absence of any job info indicates that the job has been successfully canceled 
line 140 : **Intially**, Python 3 is not loaded. 

Episode : Accessing software
line 45: (Fastest **Fourer** Transform in the West) software library **availble** for it to 
line 52: it contains the settings required to run a software **packace** 
line 65: may start out with an empty **environemnt,**
line 172: `$PATH` is a special **ennvironment** variable

Episode : Using resources effectively
line 59: You'll need to figure out a good amount of resources to ask **for for** this first "test run".

Episode : Using shared resources responsibly
line 13: "Understand how to **conver** many files to a single archive file using tar."
line 127: submit a short **trunctated** test to ensure that 
line 156: In all these cases, the helpdesk of the system you are using **shoud** be 

Episode: How does parallel computing work
line 91: If you look at the **souce** code.

Episode: Understanding what resources to use
line 20: Specifically what resources do you need initially and for parallel **applicatiosns.**
line 22: Remember the basic resources that are **mananged** by the scheduler on a HPC system are
line 83: such as this **exampler** for running the 3D animation software Maya.
line 99: **NOTE: This is nice as it automatically creates a **seperate** timing log file
Just after the references, Key Points
•	Basic benchmarking allows you to use HPC resources more **effecively.**

Episode: Bootstrapping your use of HPC
line 21: This session is designed to give you the **opprotunity** to explore these questions and

**Comment by Sabryr** [comment]
Thank you. I fixed the issues reported for https://hpc-carpentry.github.io/hpc-intro/

However, for "Introduction to High-Performance Computing Link : https://epcced.github.io/hpc-intro/" I do not think we can fix those here.

**Comment by Afrah-Khairallah** [comment]
Thank you for your response 👍 

About the other link https://epcced.github.io/hpc-intro/ sorry, i thought the lessons were under the same authors. 

Regards
