### ISSUE TITLE
Make Working on a cluster more universal

### ISSUE THREAD

**Issue by Sabryr** [hpc-carpentry/hpc-intro#94]

**Comment by Sabryr** [comment]
1. ls command when logged in to the cluster:
current text "There is nothing displayed. ". This is not the case in our cluster and a README files and a folder called nobackup is displayed for the first time user

**Comment by CarrieBrown** [comment]
Perhaps use `ls -a`. This way there will (usually) be at least 1 file displayed.

**Comment by psteinb** [comment]
Or make the output site dependent through a `{{ site.ls_user_home_output }}`? What do you think?

**Comment by Sabryr** [comment]
on : https://sabryr.github.io/hpc-intro/13-scheduler/index.html
Job environment variables section. "SLURM_CPUS_PER_TASK" does not get set in our clusters unless "#SBATCH --cpus-per-task=x" use in the job script.

**Comment by Sabryr** [comment]
May be better to use descriptive argument names instead of short hand. 
e.g.
--nodes instead of -n  
--cpus-per-task  instead of -c 

This gives a better understanding on request

**Comment by psteinb** [comment]
Definitely! I agree.
